--------------------------------------------------------
--  파일이 생성됨 - 화요일-6월-15-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence EMP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EMP_SEQ"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 328 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_BOARD_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOOKING_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_BOOKING_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 85 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CINEMA_INFO_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_CINEMA_INFO_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMMENT_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_COMMENT_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DISTRIBUTION_COM_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_DISTRIBUTION_COM_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FILM_INFO_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_FILM_INFO_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_GENRE_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_GENRE_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_INFO_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_INFO_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MEMBER_BOARD_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_MEMBER_BOARD_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MEMBER_INFO1_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_MEMBER_INFO1_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MEMBER_INFO_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_MEMBER_INFO_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MOVIE_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_MOVIE_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MOVIE_INFOR_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_MOVIE_INFOR_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MOVIE_INFO_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_MOVIE_INFO_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MOVIE_SCHEDULE_DATE_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_MOVIE_SCHEDULE_DATE_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 19 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MOVIE_SCHEDULE_TIME_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_MOVIE_SCHEDULE_TIME_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 72 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MY_RATING_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_MY_RATING_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRICE_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PRICE_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PUBLIC_RAITING_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PUBLIC_RAITING_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RAITING_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_RAITING_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SCREENING_TIME_TABLE
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_SCREENING_TIME_TABLE"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 22 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SEAT_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_SEAT_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 333 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_THEATER_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_THEATER_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TIME_TABLE_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_TIME_TABLE_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USERS_RATING_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_USERS_RATING_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USER_BOARD_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_USER_BOARD_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USER_COMMENT_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_USER_COMMENT_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USER_RATING_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_USER_RATING_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_VIEWING_CLASS_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_VIEWING_CLASS_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_WISH_LIST_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_WISH_LIST_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

  CREATE TABLE "BOOKING" 
   (	"IDX" NUMBER, 
	"BOOKING_THEATER" VARCHAR2(50 BYTE), 
	"BOOKING_TIME" VARCHAR2(50 BYTE), 
	"BOOKING_SEAT" VARCHAR2(50 BYTE), 
	"BOOKING_RANKING" NUMBER, 
	"MEMBER_ID" NUMBER, 
	"BOOKING_MOVIE" VARCHAR2(50 BYTE), 
	"BOOKING_YEAR" NUMBER, 
	"BOOKING_MONTH" NUMBER, 
	"BOOKING_DATE" NUMBER, 
	"BOOKING_PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER_INFO
--------------------------------------------------------

  CREATE TABLE "MEMBER_INFO" 
   (	"IDX" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE), 
	"USER_PWD" VARCHAR2(50 BYTE), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"PHONE_NUM" NUMBER, 
	"USER_EMAIL" VARCHAR2(50 BYTE), 
	"USER_PROFILE" VARCHAR2(50 BYTE), 
	"CREATE_DATE" DATE, 
	"USER_GENDER" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOVIE
--------------------------------------------------------

  CREATE TABLE "MOVIE" 
   (	"IDX" NUMBER, 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOVIE_SCHEDULE_DATE
--------------------------------------------------------

  CREATE TABLE "MOVIE_SCHEDULE_DATE" 
   (	"IDX" NUMBER, 
	"SCREENING_YEAR" NUMBER, 
	"SCREENING_MONTH" NUMBER, 
	"SCREENING_DATE" NUMBER, 
	"THEATER_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOVIE_SCHEDULE_TIME
--------------------------------------------------------

  CREATE TABLE "MOVIE_SCHEDULE_TIME" 
   (	"IDX" NUMBER, 
	"SCREENING_TIME" VARCHAR2(50 BYTE), 
	"DATE_ID" NUMBER, 
	"MOVIE_IDX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MY_RATING
--------------------------------------------------------

  CREATE TABLE "MY_RATING" 
   (	"IDX" NUMBER, 
	"MOVIE_NAME" VARCHAR2(40 BYTE), 
	"RATING" NUMBER, 
	"MEMBER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRICE
--------------------------------------------------------

  CREATE TABLE "PRICE" 
   (	"IDX" NUMBER, 
	"SEAT_PRICE" NUMBER, 
	"SEAT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCREENING_TIMETABLE
--------------------------------------------------------

  CREATE TABLE "SCREENING_TIMETABLE" 
   (	"MD_ID" NUMBER, 
	"MT_ID" NUMBER, 
	"상영관" VARCHAR2(20 BYTE), 
	"영화" VARCHAR2(50 BYTE), 
	"상영년도" NUMBER, 
	"상영월" NUMBER, 
	"상영일" NUMBER, 
	"상영시간" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEAT
--------------------------------------------------------

  CREATE TABLE "SEAT" 
   (	"IDX" NUMBER, 
	"SEAT_CODE" VARCHAR2(20 BYTE), 
	"THEATER_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table THEATER
--------------------------------------------------------

  CREATE TABLE "THEATER" 
   (	"THEATER_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_M_MAPPING
--------------------------------------------------------

  CREATE TABLE "T_M_MAPPING" 
   (	"MOVIE_ID" NUMBER, 
	"THEATER_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_BOARD
--------------------------------------------------------

  CREATE TABLE "USER_BOARD" 
   (	"IDX" NUMBER, 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"CREATE_DATE" DATE, 
	"MEMBER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_COMMENT
--------------------------------------------------------

  CREATE TABLE "USER_COMMENT" 
   (	"IDX" NUMBER, 
	"USER_COMMENT" VARCHAR2(500 BYTE), 
	"CREATE_DATE" DATE, 
	"BOARD_ID" NUMBER, 
	"MEMBER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WISH_LIST
--------------------------------------------------------

  CREATE TABLE "WISH_LIST" 
   (	"IDX" NUMBER, 
	"WISH_LIST" VARCHAR2(50 BYTE), 
	"MEMBER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View VIEWING_BOOKING
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VIEWING_BOOKING" ("IDX", "BOOKING_THEATER", "BOOKING_TIME", "BOOKING_SEAT", "BOOKING_RANKING", "MEMBER_ID", "BOOKING_MOVIE", "BOOKING_YEAR", "BOOKING_MONTH", "BOOKING_DATE", "BOOKING_PRICE") AS 
  select "IDX","BOOKING_THEATER","BOOKING_TIME","BOOKING_SEAT","BOOKING_RANKING","MEMBER_ID","BOOKING_MOVIE","BOOKING_YEAR","BOOKING_MONTH","BOOKING_DATE","BOOKING_PRICE" from booking
;
--------------------------------------------------------
--  DDL for View VIEWING_TIMETABLE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VIEWING_TIMETABLE" ("IDX", "THEATER_CODE", "NAME", "SCREENING_YEAR", "SCREENING_MONTH", "SCREENING_DATE", "SCREENING_TIME") AS 
  select  MT.idx,  theater_code, name, screening_year, screening_month, screening_date, screening_time
from theater T
left join t_m_mapping TM on T.theater_code= TM.theater_code 
left join movie M on TM.movie_id=M.idx
left join movie_schedule_date MD on T.theater_code= MD.theater_code 
inner join movie_schedule_time MT on M.idx= MT.movie_idx and MD.idx=MT.date_id
order by 2,6,7
;
REM INSERTING into BOOKING
SET DEFINE OFF;
REM INSERTING into MEMBER_INFO
SET DEFINE OFF;
Insert into MEMBER_INFO (IDX,USER_ID,USER_PWD,USER_NAME,PHONE_NUM,USER_EMAIL,USER_PROFILE,CREATE_DATE,USER_GENDER) values (1,'tmdwns0531','1q2w3e@','민승준',1033659545,'tmdwns0531@naver.com','user',to_date('21/06/13','RR/MM/DD'),'man');
REM INSERTING into MOVIE
SET DEFINE OFF;
Insert into MOVIE (IDX,NAME) values (1,'크루엘라');
Insert into MOVIE (IDX,NAME) values (2,'컨저링3: 악마가 시켰다');
Insert into MOVIE (IDX,NAME) values (3,'분노의 질주: 더 얼티메이트');
Insert into MOVIE (IDX,NAME) values (4,'파이프라인');
Insert into MOVIE (IDX,NAME) values (5,'극장판 귀멸의 칼날: 무한열차편');
Insert into MOVIE (IDX,NAME) values (6,'프로페서 앤 매드맨');
Insert into MOVIE (IDX,NAME) values (7,'굴뚝마을의 푸펠');
Insert into MOVIE (IDX,NAME) values (8,'뱅드림! 로젤리아 에피소드Ⅰ: 약속');
Insert into MOVIE (IDX,NAME) values (9,'비와 당신의 이야기');
Insert into MOVIE (IDX,NAME) values (10,'보이저스');
REM INSERTING into MOVIE_SCHEDULE_DATE
SET DEFINE OFF;
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (8,2021,6,25,'A');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (9,2021,6,26,'A');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (10,2021,6,25,'B');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (11,2021,6,25,'C');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (12,2021,6,25,'D');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (13,2021,6,25,'E');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (14,2021,6,25,'F');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (15,2021,6,25,'G');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (16,2021,6,26,'C');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (17,2021,6,26,'E');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (18,2021,6,26,'G');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (1,2021,6,24,'A');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (2,2021,6,24,'B');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (3,2021,6,24,'C');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (4,2021,6,24,'D');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (5,2021,6,24,'E');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (6,2021,6,24,'F');
Insert into MOVIE_SCHEDULE_DATE (IDX,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,THEATER_CODE) values (7,2021,6,24,'G');
REM INSERTING into MOVIE_SCHEDULE_TIME
SET DEFINE OFF;
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (22,'17:00',1,1);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (23,'14:30',2,1);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (24,'17:30',2,2);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (25,'21:00',2,3);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (26,'14:00',3,1);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (27,'20:30',3,2);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (28,'17:40',4,4);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (29,'21:00',4,5);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (30,'19:00',5,5);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (31,'19:00',6,5);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (32,'22:20',7,1);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (33,'23:10',3,1);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (34,'16:00',8,1);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (35,'13:30',8,2);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (36,'9:30',8,4);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (37,'19:10',8,4);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (38,'10:10',9,4);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (39,'14:30',9,2);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (40,'18:00',9,1);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (41,'11:20',10,2);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (42,'15:00',10,1);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (43,'23:10',10,4);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (44,'9:20',11,3);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (45,'12:40',11,5);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (46,'16:20',11,4);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (47,'20:20',11,6);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (48,'10:30',16,4);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (49,'14:10',16,2);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (50,'18:10',16,5);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (51,'09:10',12,6);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (52,'13:30',12,9);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (53,'17:30',12,10);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (54,'10:30',17,9);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (55,'15:10',17,8);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (56,'21:10',17,10);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (57,'13:10',14,8);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (58,'18:10',14,9);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (59,'22:10',14,10);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (60,'11:30',18,5);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (61,'15:30',18,6);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (62,'19:10',18,3);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (63,'09:40',15,2);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (64,'14:10',15,6);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (65,'18:00',15,5);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (66,'21:00',15,3);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (67,'22:30',11,1);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (68,'19:30',8,5);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (69,'21:20',9,2);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (70,'18:10',10,4);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (71,'20:10',10,3);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (1,'09:00',1,2);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (2,'11:30',1,5);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (3,'14:00',1,1);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (4,'09:00',2,5);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (5,'11:30',2,1);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (6,'09:00',3,6);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (7,'11:40',3,2);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (8,'17:30',3,1);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (9,'10:00',4,6);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (10,'15:00',4,2);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (11,'09:30',5,4);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (12,'13:30',5,3);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (13,'16:30',5,7);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (14,'10:00',6,3);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (15,'13:30',6,4);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (16,'16:30',6,7);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (17,'09:30',7,9);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (18,'13:30',7,3);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (19,'16:00',7,8);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (20,'17:30',7,4);
Insert into MOVIE_SCHEDULE_TIME (IDX,SCREENING_TIME,DATE_ID,MOVIE_IDX) values (21,'19:30',7,10);
REM INSERTING into MY_RATING
SET DEFINE OFF;
REM INSERTING into PRICE
SET DEFINE OFF;
Insert into PRICE (IDX,SEAT_PRICE,SEAT_ID) values (1,8000,1);
Insert into PRICE (IDX,SEAT_PRICE,SEAT_ID) values (2,8000,10);
Insert into PRICE (IDX,SEAT_PRICE,SEAT_ID) values (3,10000,19);
Insert into PRICE (IDX,SEAT_PRICE,SEAT_ID) values (4,10000,28);
Insert into PRICE (IDX,SEAT_PRICE,SEAT_ID) values (5,12000,37);
Insert into PRICE (IDX,SEAT_PRICE,SEAT_ID) values (6,12000,46);
REM INSERTING into SCREENING_TIMETABLE
SET DEFINE OFF;
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (1,1,'A','컨저링: 악마가 시켰다',2021,6,24,'09:00');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (1,2,'A','극장판 귀멸의 칼날: 무한열차편',2021,6,24,'11:30');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (1,3,'A','크루엘라',2021,6,24,'14:00');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (2,4,'B','극장판 귀멸의 칼날: 무한열차편',2021,6,24,'09:00');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (2,5,'B','크루엘라',2021,6,24,'11:30');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (3,6,'C','프로페서 앤 매드맨',2021,6,24,'09:00');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (3,7,'C','컨저링: 악마가 시켰다',2021,6,24,'11:40');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (3,8,'C','크루엘라',2021,6,24,'15:00');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (4,9,'D','프로페서 앤 매드맨',2021,6,24,'10:00');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (4,10,'D','컨저링: 악마가 시켰다',2021,6,24,'15:00');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (5,11,'E','파이프라인',2021,6,24,'09:30');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (5,13,'E','굴뚝마을의 푸펠',2021,6,24,'16:30');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (5,12,'E','분노의 질주: 더 얼티메이트',2021,6,24,'13:30');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (6,14,'F','분노의 질주: 더 얼티메이트',2021,6,24,'10:00');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (6,15,'F','파이프라인',2021,6,24,'13:30');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (6,16,'F','굴뚝마을의 푸펠',2021,6,24,'16:30');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (7,17,'G','비와 당신의 이야기',2021,6,24,'09:30');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (7,18,'G','분노의 질주: 더 얼티메이트',2021,6,24,'13:30');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (7,20,'G','파이프라인',2021,6,24,'17:30');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (7,19,'G','뱅드림! 로젤리아 에피소드Ⅰ: 약속',2021,6,24,'16:00');
Insert into SCREENING_TIMETABLE (MD_ID,MT_ID,"상영관","영화","상영년도","상영월","상영일","상영시간") values (7,21,'G','보이저스',2021,6,24,'19:30');
REM INSERTING into SEAT
SET DEFINE OFF;
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (1,'A1','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (2,'A2','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (3,'A3','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (4,'A4','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (5,'A5','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (6,'A6','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (7,'A7','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (8,'A8','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (9,'A9','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (10,'B1','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (11,'B2','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (12,'B3','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (13,'B4','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (14,'B5','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (15,'B6','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (16,'B7','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (17,'B8','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (18,'B9','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (19,'C1','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (20,'C2','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (21,'C3','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (22,'C4','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (23,'C5','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (24,'C6','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (25,'C7','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (26,'C8','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (27,'C9','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (28,'D1','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (29,'D2','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (30,'D3','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (31,'D4','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (32,'D5','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (33,'D6','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (34,'D7','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (35,'D8','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (36,'D9','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (37,'E1','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (38,'E2','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (39,'E3','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (40,'E4','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (41,'E5','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (42,'E6','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (43,'E7','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (44,'E8','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (45,'E9','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (46,'F1','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (47,'F2','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (48,'F3','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (49,'F4','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (50,'F5','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (51,'F6','A');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (53,'A1','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (54,'A2','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (55,'A3','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (56,'A4','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (57,'A5','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (58,'A6','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (59,'A7','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (60,'A8','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (61,'A9','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (62,'B1','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (63,'B2','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (64,'B3','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (65,'B4','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (66,'B5','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (67,'B6','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (68,'B7','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (69,'B8','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (70,'B9','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (71,'C1','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (72,'C2','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (73,'C3','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (74,'C4','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (75,'C5','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (76,'C6','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (77,'C7','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (78,'C8','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (79,'C9','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (80,'D1','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (81,'D2','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (82,'D3','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (83,'D4','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (84,'D5','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (85,'D6','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (86,'D7','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (87,'D8','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (88,'D9','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (89,'E1','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (90,'E2','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (91,'E3','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (92,'E4','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (93,'E5','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (94,'E6','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (95,'E7','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (96,'E8','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (97,'E9','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (98,'F1','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (99,'F2','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (100,'F3','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (101,'F4','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (102,'F5','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (103,'F6','B');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (108,'A1','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (109,'A2','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (110,'A3','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (111,'A4','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (112,'A5','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (113,'A6','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (114,'A7','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (115,'A8','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (116,'A9','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (117,'B1','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (118,'B2','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (119,'B3','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (120,'B4','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (121,'B5','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (122,'B6','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (123,'B7','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (124,'B8','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (125,'B9','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (126,'C1','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (127,'C2','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (128,'C3','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (129,'C4','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (130,'C5','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (131,'C6','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (132,'C7','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (133,'C8','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (134,'C9','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (135,'D1','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (136,'D2','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (137,'D3','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (138,'D4','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (139,'D5','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (140,'D6','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (141,'D7','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (142,'D8','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (143,'D9','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (144,'E1','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (145,'E2','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (146,'E3','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (147,'E4','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (148,'E5','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (149,'E6','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (150,'E7','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (151,'E8','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (152,'E9','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (153,'F4','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (154,'F5','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (155,'F6','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (156,'F7','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (157,'F8','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (158,'F9','C');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (159,'A1','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (160,'A2','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (161,'A3','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (162,'A4','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (163,'A5','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (164,'A6','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (165,'A7','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (166,'A8','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (167,'A9','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (168,'B1','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (169,'B2','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (170,'B3','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (171,'B4','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (172,'B5','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (173,'B6','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (174,'B7','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (175,'B8','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (176,'B9','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (177,'C1','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (178,'C2','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (179,'C3','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (180,'C4','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (181,'C5','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (182,'C6','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (183,'C7','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (184,'C8','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (185,'C9','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (186,'D1','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (187,'D2','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (188,'D3','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (189,'D4','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (190,'D5','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (191,'D6','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (192,'D7','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (193,'D8','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (194,'D9','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (195,'E1','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (196,'E2','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (197,'E3','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (198,'E4','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (199,'E5','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (200,'E6','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (201,'E7','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (202,'E8','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (203,'E9','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (204,'F4','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (205,'F5','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (206,'F6','D');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (207,'A1','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (208,'A2','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (209,'A3','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (210,'A4','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (211,'A5','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (212,'A6','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (213,'A7','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (214,'A8','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (215,'A9','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (216,'B1','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (217,'B2','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (218,'B3','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (219,'B4','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (220,'B5','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (221,'B6','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (222,'B7','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (223,'B8','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (224,'B9','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (225,'C1','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (226,'C2','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (227,'C3','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (228,'C4','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (229,'C5','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (230,'C6','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (231,'C7','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (232,'C8','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (233,'C9','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (234,'D1','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (235,'D2','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (236,'D3','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (237,'D4','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (238,'D5','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (239,'D6','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (240,'D7','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (241,'D8','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (242,'D9','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (243,'E1','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (244,'E2','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (245,'E3','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (246,'E4','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (247,'E5','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (248,'E6','E');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (249,'A1','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (250,'A2','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (251,'A3','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (252,'A4','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (253,'A5','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (254,'A6','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (255,'B1','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (256,'B2','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (257,'B3','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (258,'B4','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (259,'B5','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (260,'B6','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (261,'B7','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (262,'B8','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (263,'B9','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (264,'C1','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (265,'C2','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (266,'C3','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (267,'C4','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (268,'C5','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (269,'C6','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (270,'C7','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (271,'C8','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (272,'C9','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (273,'D1','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (274,'D2','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (275,'D3','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (276,'D4','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (277,'D5','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (278,'D6','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (279,'D7','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (280,'D8','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (281,'D9','F');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (282,'A1','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (283,'A2','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (284,'A3','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (285,'A4','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (286,'A5','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (287,'A6','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (288,'A7','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (289,'A8','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (290,'A9','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (291,'B1','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (292,'B2','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (293,'B3','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (294,'B4','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (295,'B5','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (296,'B6','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (297,'B7','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (298,'B8','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (299,'B9','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (300,'C1','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (301,'C2','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (302,'C3','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (303,'C4','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (304,'C5','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (305,'C6','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (306,'C7','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (307,'C8','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (308,'C9','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (309,'D1','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (310,'D2','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (311,'D3','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (312,'D4','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (313,'D5','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (314,'D6','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (315,'D7','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (316,'D8','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (317,'D9','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (318,'E1','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (319,'E2','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (320,'E3','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (321,'E4','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (322,'E5','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (323,'E6','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (324,'E7','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (325,'E8','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (326,'E9','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (327,'F4','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (328,'F5','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (329,'F6','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (330,'F7','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (331,'F8','G');
Insert into SEAT (IDX,SEAT_CODE,THEATER_CODE) values (332,'F9','G');
REM INSERTING into THEATER
SET DEFINE OFF;
Insert into THEATER (THEATER_CODE) values ('A');
Insert into THEATER (THEATER_CODE) values ('B');
Insert into THEATER (THEATER_CODE) values ('C');
Insert into THEATER (THEATER_CODE) values ('D');
Insert into THEATER (THEATER_CODE) values ('E');
Insert into THEATER (THEATER_CODE) values ('F');
Insert into THEATER (THEATER_CODE) values ('G');
REM INSERTING into T_M_MAPPING
SET DEFINE OFF;
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (1,'G');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (1,'C');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (2,'B');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (4,'B');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (3,'B');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (4,'D');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (5,'D');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (5,'E');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (1,'A');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (1,'B');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (1,'C');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (2,'A');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (2,'C');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (2,'D');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (3,'E');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (3,'F');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (3,'G');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (4,'E');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (4,'F');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (4,'G');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (5,'A');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (5,'B');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (6,'C');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (6,'D');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (7,'E');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (7,'F');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (8,'G');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (9,'G');
Insert into T_M_MAPPING (MOVIE_ID,THEATER_CODE) values (10,'G');
REM INSERTING into USER_BOARD
SET DEFINE OFF;
REM INSERTING into USER_COMMENT
SET DEFINE OFF;
REM INSERTING into WISH_LIST
SET DEFINE OFF;
REM INSERTING into VIEWING_BOOKING
SET DEFINE OFF;
REM INSERTING into VIEWING_TIMETABLE
SET DEFINE OFF;
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (1,'A','컨저링3: 악마가 시켰다',2021,6,24,'09:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (2,'A','극장판 귀멸의 칼날: 무한열차편',2021,6,24,'11:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (3,'A','크루엘라',2021,6,24,'14:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (22,'A','크루엘라',2021,6,24,'17:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (35,'A','컨저링3: 악마가 시켰다',2021,6,25,'13:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (34,'A','크루엘라',2021,6,25,'16:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (68,'A','극장판 귀멸의 칼날: 무한열차편',2021,6,25,'19:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (39,'A','컨저링3: 악마가 시켰다',2021,6,26,'14:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (40,'A','크루엘라',2021,6,26,'18:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (69,'A','컨저링3: 악마가 시켰다',2021,6,26,'21:20');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (4,'B','극장판 귀멸의 칼날: 무한열차편',2021,6,24,'09:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (5,'B','크루엘라',2021,6,24,'11:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (23,'B','크루엘라',2021,6,24,'14:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (24,'B','컨저링3: 악마가 시켰다',2021,6,24,'17:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (25,'B','분노의 질주: 더 얼티메이트',2021,6,24,'21:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (41,'B','컨저링3: 악마가 시켰다',2021,6,25,'11:20');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (42,'B','크루엘라',2021,6,25,'15:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (70,'B','파이프라인',2021,6,25,'18:10');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (71,'B','분노의 질주: 더 얼티메이트',2021,6,25,'20:10');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (43,'B','파이프라인',2021,6,25,'23:10');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (6,'C','프로페서 앤 매드맨',2021,6,24,'09:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (7,'C','컨저링3: 악마가 시켰다',2021,6,24,'11:40');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (26,'C','크루엘라',2021,6,24,'14:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (26,'C','크루엘라',2021,6,24,'14:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (8,'C','크루엘라',2021,6,24,'17:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (8,'C','크루엘라',2021,6,24,'17:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (27,'C','컨저링3: 악마가 시켰다',2021,6,24,'20:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (33,'C','크루엘라',2021,6,24,'23:10');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (33,'C','크루엘라',2021,6,24,'23:10');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (47,'C','프로페서 앤 매드맨',2021,6,25,'20:20');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (67,'C','크루엘라',2021,6,25,'22:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (67,'C','크루엘라',2021,6,25,'22:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (49,'C','컨저링3: 악마가 시켰다',2021,6,26,'14:10');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (9,'D','프로페서 앤 매드맨',2021,6,24,'10:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (10,'D','컨저링3: 악마가 시켰다',2021,6,24,'15:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (28,'D','파이프라인',2021,6,24,'17:40');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (29,'D','극장판 귀멸의 칼날: 무한열차편',2021,6,24,'21:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (51,'D','프로페서 앤 매드맨',2021,6,25,'09:10');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (11,'E','파이프라인',2021,6,24,'09:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (12,'E','분노의 질주: 더 얼티메이트',2021,6,24,'13:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (13,'E','굴뚝마을의 푸펠',2021,6,24,'16:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (30,'E','극장판 귀멸의 칼날: 무한열차편',2021,6,24,'19:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (14,'F','분노의 질주: 더 얼티메이트',2021,6,24,'10:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (15,'F','파이프라인',2021,6,24,'13:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (16,'F','굴뚝마을의 푸펠',2021,6,24,'16:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (17,'G','비와 당신의 이야기',2021,6,24,'09:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (18,'G','분노의 질주: 더 얼티메이트',2021,6,24,'13:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (19,'G','뱅드림! 로젤리아 에피소드Ⅰ: 약속',2021,6,24,'16:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (20,'G','파이프라인',2021,6,24,'17:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (21,'G','보이저스',2021,6,24,'19:30');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (32,'G','크루엘라',2021,6,24,'22:20');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (66,'G','분노의 질주: 더 얼티메이트',2021,6,25,'21:00');
Insert into VIEWING_TIMETABLE (IDX,THEATER_CODE,NAME,SCREENING_YEAR,SCREENING_MONTH,SCREENING_DATE,SCREENING_TIME) values (62,'G','분노의 질주: 더 얼티메이트',2021,6,26,'19:10');
--------------------------------------------------------
--  DDL for Index PK_THAETER_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_THAETER_1" ON "THEATER" ("THEATER_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007440
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007440" ON "BOOKING" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007449
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007449" ON "MEMBER_INFO" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007450
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007450" ON "MEMBER_INFO" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007453
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007453" ON "MOVIE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007457
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007457" ON "MOVIE_SCHEDULE_DATE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007460
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007460" ON "MOVIE_SCHEDULE_TIME" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007465
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007465" ON "MY_RATING" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007469
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007469" ON "PRICE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007473
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007473" ON "SEAT" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007484
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007484" ON "USER_BOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007490
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007490" ON "USER_COMMENT" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007494
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007494" ON "WISH_LIST" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007440
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007440" ON "BOOKING" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007449
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007449" ON "MEMBER_INFO" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007450
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007450" ON "MEMBER_INFO" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007453
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007453" ON "MOVIE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007457
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007457" ON "MOVIE_SCHEDULE_DATE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007460
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007460" ON "MOVIE_SCHEDULE_TIME" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007465
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007465" ON "MY_RATING" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007469
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007469" ON "PRICE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007473
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007473" ON "SEAT" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_THAETER_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_THAETER_1" ON "THEATER" ("THEATER_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007484
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007484" ON "USER_BOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007490
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007490" ON "USER_COMMENT" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007494
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007494" ON "WISH_LIST" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "BOOKING" MODIFY ("BOOKING_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOOKING" MODIFY ("BOOKING_DATE" NOT NULL ENABLE);
  ALTER TABLE "BOOKING" MODIFY ("BOOKING_MOVIE" NOT NULL ENABLE);
  ALTER TABLE "BOOKING" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKING" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKING" MODIFY ("BOOKING_MONTH" NOT NULL ENABLE);
  ALTER TABLE "BOOKING" MODIFY ("BOOKING_SEAT" NOT NULL ENABLE);
  ALTER TABLE "BOOKING" MODIFY ("BOOKING_TIME" NOT NULL ENABLE);
  ALTER TABLE "BOOKING" MODIFY ("BOOKING_YEAR" NOT NULL ENABLE);
  ALTER TABLE "BOOKING" MODIFY ("BOOKING_THEATER" NOT NULL ENABLE);
  ALTER TABLE "BOOKING" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER_INFO
--------------------------------------------------------

  ALTER TABLE "MEMBER_INFO" ADD UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MEMBER_INFO" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MEMBER_INFO" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER_INFO" MODIFY ("USER_PROFILE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER_INFO" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MEMBER_INFO" MODIFY ("PHONE_NUM" NOT NULL ENABLE);
  ALTER TABLE "MEMBER_INFO" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "MEMBER_INFO" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "MEMBER_INFO" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MEMBER_INFO" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOVIE
--------------------------------------------------------

  ALTER TABLE "MOVIE" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOVIE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MOVIE" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOVIE_SCHEDULE_DATE
--------------------------------------------------------

  ALTER TABLE "MOVIE_SCHEDULE_DATE" MODIFY ("SCREENING_DATE" NOT NULL ENABLE);
  ALTER TABLE "MOVIE_SCHEDULE_DATE" MODIFY ("SCREENING_MONTH" NOT NULL ENABLE);
  ALTER TABLE "MOVIE_SCHEDULE_DATE" MODIFY ("SCREENING_YEAR" NOT NULL ENABLE);
  ALTER TABLE "MOVIE_SCHEDULE_DATE" MODIFY ("THEATER_CODE" NOT NULL ENABLE);
  ALTER TABLE "MOVIE_SCHEDULE_DATE" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOVIE_SCHEDULE_DATE" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOVIE_SCHEDULE_TIME
--------------------------------------------------------

  ALTER TABLE "MOVIE_SCHEDULE_TIME" MODIFY ("MOVIE_IDX" NOT NULL ENABLE);
  ALTER TABLE "MOVIE_SCHEDULE_TIME" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOVIE_SCHEDULE_TIME" MODIFY ("DATE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOVIE_SCHEDULE_TIME" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "MOVIE_SCHEDULE_TIME" MODIFY ("SCREENING_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MY_RATING
--------------------------------------------------------

  ALTER TABLE "MY_RATING" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MY_RATING" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "MY_RATING" MODIFY ("RATING" NOT NULL ENABLE);
  ALTER TABLE "MY_RATING" MODIFY ("MOVIE_NAME" NOT NULL ENABLE);
  ALTER TABLE "MY_RATING" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRICE
--------------------------------------------------------

  ALTER TABLE "PRICE" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRICE" MODIFY ("SEAT_ID" NOT NULL ENABLE);
  ALTER TABLE "PRICE" MODIFY ("SEAT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "PRICE" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SCREENING_TIMETABLE
--------------------------------------------------------

  ALTER TABLE "SCREENING_TIMETABLE" MODIFY ("상영관" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEAT
--------------------------------------------------------

  ALTER TABLE "SEAT" MODIFY ("THEATER_CODE" NOT NULL ENABLE);
  ALTER TABLE "SEAT" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SEAT" MODIFY ("SEAT_CODE" NOT NULL ENABLE);
  ALTER TABLE "SEAT" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table THEATER
--------------------------------------------------------

  ALTER TABLE "THEATER" MODIFY ("THEATER_CODE" NOT NULL ENABLE);
  ALTER TABLE "THEATER" ADD CONSTRAINT "PK_THAETER_1" PRIMARY KEY ("THEATER_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_M_MAPPING
--------------------------------------------------------

  ALTER TABLE "T_M_MAPPING" MODIFY ("THEATER_CODE" NOT NULL ENABLE);
  ALTER TABLE "T_M_MAPPING" MODIFY ("MOVIE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_BOARD
--------------------------------------------------------

  ALTER TABLE "USER_BOARD" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USER_BOARD" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "USER_BOARD" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "USER_BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "USER_BOARD" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_COMMENT
--------------------------------------------------------

  ALTER TABLE "USER_COMMENT" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USER_COMMENT" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "USER_COMMENT" MODIFY ("BOARD_ID" NOT NULL ENABLE);
  ALTER TABLE "USER_COMMENT" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "USER_COMMENT" MODIFY ("USER_COMMENT" NOT NULL ENABLE);
  ALTER TABLE "USER_COMMENT" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WISH_LIST
--------------------------------------------------------

  ALTER TABLE "WISH_LIST" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "WISH_LIST" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "WISH_LIST" MODIFY ("WISH_LIST" NOT NULL ENABLE);
  ALTER TABLE "WISH_LIST" MODIFY ("IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "BOOKING" ADD FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "MEMBER_INFO" ("IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOVIE_SCHEDULE_DATE
--------------------------------------------------------

  ALTER TABLE "MOVIE_SCHEDULE_DATE" ADD CONSTRAINT "FK_THEATER_1" FOREIGN KEY ("THEATER_CODE")
	  REFERENCES "THEATER" ("THEATER_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOVIE_SCHEDULE_TIME
--------------------------------------------------------

  ALTER TABLE "MOVIE_SCHEDULE_TIME" ADD CONSTRAINT "FK_TIME_MOVIE_1" FOREIGN KEY ("MOVIE_IDX")
	  REFERENCES "MOVIE" ("IDX") ENABLE;
  ALTER TABLE "MOVIE_SCHEDULE_TIME" ADD FOREIGN KEY ("DATE_ID")
	  REFERENCES "MOVIE_SCHEDULE_DATE" ("IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MY_RATING
--------------------------------------------------------

  ALTER TABLE "MY_RATING" ADD CONSTRAINT "FK_MY_RATING_MEMBER_ID_1" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "MEMBER_INFO" ("IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRICE
--------------------------------------------------------

  ALTER TABLE "PRICE" ADD FOREIGN KEY ("SEAT_ID")
	  REFERENCES "SEAT" ("IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEAT
--------------------------------------------------------

  ALTER TABLE "SEAT" ADD CONSTRAINT "FK_THEATER_SEAT_1" FOREIGN KEY ("THEATER_CODE")
	  REFERENCES "THEATER" ("THEATER_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_M_MAPPING
--------------------------------------------------------

  ALTER TABLE "T_M_MAPPING" ADD CONSTRAINT "FK_THEATER_MAP_1" FOREIGN KEY ("THEATER_CODE")
	  REFERENCES "THEATER" ("THEATER_CODE") ENABLE;
  ALTER TABLE "T_M_MAPPING" ADD FOREIGN KEY ("MOVIE_ID")
	  REFERENCES "MOVIE" ("IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_BOARD
--------------------------------------------------------

  ALTER TABLE "USER_BOARD" ADD FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "MEMBER_INFO" ("IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_COMMENT
--------------------------------------------------------

  ALTER TABLE "USER_COMMENT" ADD FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "MEMBER_INFO" ("IDX") ENABLE;
  ALTER TABLE "USER_COMMENT" ADD FOREIGN KEY ("BOARD_ID")
	  REFERENCES "USER_BOARD" ("IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WISH_LIST
--------------------------------------------------------

  ALTER TABLE "WISH_LIST" ADD FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "MEMBER_INFO" ("IDX") ENABLE;
